version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    ignore:
     - dependency-name: github.com/spf13/cobra
     - dependency-name: github.com/spf13/pflag
     - dependency-name: github.com/Masterminds/semver/v3
     - dependency-name: go.opentelemetry.io/otel
     - dependency-name: github.com/prometheus/client_golang
    groups:
      aws:
        patterns:
          - "github.com/aws/aws-sdk-go-v2/*"
      test:
        patterns:
          - "github.com/testcontainers/*"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
