kind: Pod
apiVersion: v1
metadata:
  name: cachesrv
  labels:
    app: cachesrv
spec:
  containers:
  - name: cachesrv
    image: grafana/k6build
    imagePullPolicy: Never
    command: ["k6build", "cache", "--log-level", "DEBUG", "--download-url", "http://cachesrv:9000/cache"]

---
kind: Service
apiVersion: v1
metadata:
  name: cachesrv
spec:
  selector:
    app: cachesrv
  type: LoadBalancer
  ports:
  - port: 9000

---
kind: Pod
apiVersion: v1
metadata:
  name: k6build
  labels:
    app: k6build
spec:
  containers:
  - name: buildsrv
    image: grafana/k6build
    imagePullPolicy: Never
    command:
    - "k6build"
    - "server"
    - "--verbose"
    - "--log-level"
    - "DEBUG"
    - "--cache-url"
    - "http://cachesrv:9000/cache"
    - "-e"
    - "CGO_ENABLED=1"
    - "--catalog"
    - "catalog.json"
    volumeMounts:
    - mountPath: "/home/k6build"
      name: catalog
      readOnly: true
    - mountPath: "/home/k6build/.cache"
      name: gocache
  volumes:
  - name: catalog
    configMap:
      name: k6build-catalog
  - name: gocache
    emptyDir: {}

---
kind: Service
apiVersion: v1
metadata:
  name: k6build
spec:
  selector:
    app: k6build
  type: LoadBalancer
  ports:
  - port: 8000
