name: publish

on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: grafana/k6build

jobs:
  publish-images:
    runs-on: ubuntu-x64
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
        with:
          version: v0.37.1
          cache-binary: false
      - name: Log into ghcr.io
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        run: |
          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
             IMAGE_VERSION=$GITHUB_REF_NAME
          else
             IMAGE_VERSION='latest'
          fi
          IMAGE_TAG="$REGISTRY/$IMAGE_NAME:${IMAGE_VERSION}"
          docker buildx build -t $IMAGE_TAG --platform=linux/amd64,linux/arm64 --push .
